version: "3.11"

services:
  web:
    build:
      context: ..
      dockerfile: devops/Dockerfile
      args:
        DEV: "true"
    ports:
      - "8000:8000"
    volumes:
      - ../cinephile_project:/cinephile_project
      - static_volume:/cinephile_project/static
      - media_volume:/cinephile_project/media
    environment:
      - DEBUG=True
    command: python /cinephile_project/manage.py runserver 0.0.0.0:8000

volumes:
  static_volume:
  media_volume:
